### ISSUE TITLE
convert smaller calibre templates to yaml to demo as an example.

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#543]
related to requirement to open up API so anyone can use it
what should the template format be? - yaml 
need to support mark down
support different options for code lists - existing concept, csv file etc

**Comment by ieuans** [comment]
Example structure of phenotype:

```
phenotype_id: 83NbVPhy532ogkJrxzUmoy
phenoflowid: 1
title: COVID-19 Infection
author: 
 - author_1
 - author_2
sex: Female, Male
valid_event_data_range: 01/01/2020 - 31/10/2020
type: Disease or Syndrome
description: "Multiline description,
  newlines work, escapes work \\n incl. \"quotes\"\n"
implementation: ""
source_reference: "https://portal.caliberresearch.org/phenotypes/CVDCOVIDUK-COVID19-83NbVPhy532ogkJrxzUmoy"
validation_performed: false
validation: example validation
paper_published: false
primary_publications: "primary paper reference"
publication_link: ""
publication_doi: ""
publications:
 - "publication_1"
 - "publication_2"
concept_informations:
  - 123
  - 245
  - 678
data_sources: 
  "GPES Data for Pandemic Planning and Research (COVID-19)":
    id: 696cfc9f-090d-4328-94ac-140760a77c73
    url: "https://web.www.healthdatagateway.org/dataset/696cfc9f-090d-4328-94ac-140760a77c73"
    description: Example of single-line description
  "Hospital Episode Statistics Admitted Patient Care":
    id: 2b6409db-a669-4bef-9fd5-39c2b6f8d5e9
    url: "https://web.www.healthdatagateway.org/dataset/2b6409db-a669-4bef-9fd5-39c2b6f8d5e9"
    description: "Example of description containing :"
  "Civil Registration - Deaths":
    id: 
    url: 
    description: "multi-line,
      description"
```

May be worth asking researchers to enclose all values in quotes as certain characters would break the structure, e.g. :, >, |, etc
